export default Object.freeze({
  IN_PROGRESS: "IN_PROGRESS",
  NO_CONNECTION: "NO_CONNECTION",
  EXPENSIVE_CONNECTION: "EXPENSIVE_CONNECTION",
  NO_FREE_SPACE: "NO_FREE_SPACE",
  DONE: "DONE",
});

export const FREE_SPACE_THRESHOLD = 200 * 1000 * 1000; // 200 MB
