export const SETTINGS_OPTIONS = Object.freeze({
  STORE_FAVOURITES_OFFLINE: "STORE_FAVOURITES_OFFLINE",
  STORE_FILES: "STORE_FILES",
  DOWNLOAD_FILES_EXPENSIVE: "DOWNLOAD_FILES_EXPENSIVE",
});

export const DEFAULT_VALUES = Object.freeze({
  STORE_FAVOURITES_OFFLINE: false,
  STORE_FILES: false,
  DOWNLOAD_FILES_EXPENSIVE: false,
});
