name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: echo "No tests at the moment :("

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Publish to expo
        run: |
          npx expo login -u ${{ secrets.NPX_USERNAME }} -p ${{ secrets.NPX_PASSWORD }}
          npx expo publish --non-interactive
